spring:
  application:
    name: HexagonalDDD-Verification-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/verification_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092